### PR TITLE
README: Add personal portfolio project

### PR DESCRIPTION
**Pull request by naveenkumarsangi**
Here's https://naveen.cloud

### CODE REVIEW

**Comment by abh3po** [comment]
nice ;)

**Comment by naveenkumarsangi** [comment]
Any specific reason for not merging this yet? ^^ 😅

**Comment by abh3po** [comment]
@nkprince007 as the rules state you have toget atleast 15 happy reactions (a cheap method to get validations :P) before the  PR can be merged

**Comment by abh3po** [comment]
i see that you have 2 unique ones already :P 13 more to go!!

**Comment by abh3po** [comment]
declining. Past deadline. few reacts

**Comment by naveenkumarsangi** [comment]
😥 Getting reacts on GitHub isn't easy. 
It's not some Facebook or Twitter to get instant reviews.
@abhsag24 this is unfair.

**Comment by abh3po** [comment]
@nkprince007 raise A PR to change the READEM? :P and change the rules?

**Comment by abh3po** [comment]
also any other suggestions would also work well

**Pull request closed without merging**
